### ISSUE TITLE
Menu items that are still being downloaded

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/mobicage-ios-client#121]
New users complain that buttons like 'Trash Calendar' don't work the first minute(s) after the installation.

We suggest to update the popup text to:
- EN: Please wait. The "%$1s" application is still downloading.
- NL: Even geduld. De "%$1s"-applicatie is nog aan het downloaden.

This way they'll probably wait a little bit longer than with the old text.

![2019-05-27 11 25 06](https://user-images.githubusercontent.com/17762105/58410482-9242f700-8072-11e9-9a7d-82f7c6b899fe.jpg)

**Comment by RubenMattan** [comment]
We don't always have an application name. so we need an error message that can be used in both cases
