### ISSUE TITLE
Replace UIWebView with WKWebView

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/mobicage-ios-client#145]
ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

**Comment by RubenMattan** [comment]
![Screenshot 2019-09-06 at 11 51 41](https://user-images.githubusercontent.com/1122760/64419265-d051ad00-d09c-11e9-81ca-69d738cd80e3.png)

**Comment by RubenMattan** [comment]
https://github.com/our-city-app/mobicage-ios-client/pull/146

**Comment by bart-at-mobicage** [comment]
comments posted @ #146
