### ISSUE TITLE
Playing YouTube videos in news feed

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/mobicage-ios-client#149]
See https://github.com/hmhv/YoutubePlayer-in-WKWebView, https://github.com/our-city-app/oca-backend/pull/1446 and https://github.com/our-city-app/mobicage-android-client/pull/173

**Comment by RubenMattan** [comment]
@bart-at-mobicage Can u please show a demo of the android implementation to Tom. If this is okay i will start on iOS

**Comment by bart-at-mobicage** [comment]
Tom approved the android version. Only thing that had to change was the mute button, which was a bit hidden.

**Comment by RubenMattan** [comment]
https://github.com/our-city-app/mobicage-ios-client/pull/154
