### ISSUE TITLE
News text encode incorrect

### ISSUE THREAD

**Issue by lucasvanhalst** [our-city-app/mobicage-ios-client#40]
---

Migrated from https://github.com/rogerthat-platform/rogerthat-ios-client/issues/113
Originally created by @RubenMattan on *Fri, 14 Jul 2017 11:58:39 GMT*

---
![screen shot 2017-07-14 at 13 57 50](https://user-images.githubusercontent.com/1122760/28211365-86224498-689c-11e7-8002-5f674df0fe96.png)

**Comment by lucasvanhalst** [comment]
---

Migrated from https://github.com/rogerthat-platform/rogerthat-ios-client/issues/113#issuecomment-316695488
Originally created by @bart-at-mobicage on *Thu, 20 Jul 2017 13:00:27 GMT*

---
It's seems it are emoticons which should be available on iOS

![screen shot 2017-07-20 at 14 36 06](https://user-images.githubusercontent.com/17762105/28418477-1d219808-6d5c-11e7-8ee8-4c479aac7ff1.png)

**Comment by bart-at-mobicage** [comment]
Same problem when setting chat topic. It works when entered on Android, but not when entered on iOS
