### ISSUE TITLE
In the TF app, the search doesnt limit to organization type

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/mobicage-ios-client#52]
Maybe related to custom look & feel

Eg. in the TF app, when opening the search under "TF Foundation" (community_services), you see all services in the TF app. The organization_type sent to the server is -1.

**Comment by RubenMattan** [comment]
Fixed by https://github.com/our-city-app/mobicage-ios-client/commit/ab6be49cc769e31d91f80d36872f5ef347f545b3
