### ISSUE TITLE
news item with markdown is cropped

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/mobicage-ios-client#62]
Looks like the size calculation is done using normal font sizes.

![img_fdf80dffae7f-1](https://user-images.githubusercontent.com/17762105/45557980-20f24980-b83f-11e8-856e-344462620c59.jpeg)

**Comment by bart-at-mobicage** [comment]
The font size gets messed up whenever I press "*Read more*" and start scrolling.

**Comment by RubenMattan** [comment]
Works fine on iPhone 5 (9.3) simulator

**Comment by bart-at-mobicage** [comment]
Weird. I can't reproduce it on my phone anymore. Let's close for now.

**Comment by RubenMattan** [comment]
Works fine om iPhone 6s Plus (9.3) simulator
