### ISSUE TITLE
Make gender and birthdate optional when saving your profile

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/mobicage-ios-client#77]
Let's make it optional and thus remove the popup code.

> We noticed that your app requires users to register with personal information that is not directly relevant to your app’s core functionality. Specifically, the following fields are required but do not appear to be directly relevant to your app’s core functionality:
> 
> - Date of birth 
> - Gender
> 
> **Next Steps**
> 
> To resolve this issue, please either remove all required fields that are not relevant to the app or make those fields optional. Information requested during registration must be relevant to the features the app provides.
> 
> 
> 
> Please see attached screenshot for details.

![attachment-4790712444151374264screenshot-1106-172844](https://user-images.githubusercontent.com/17762105/48121201-93e2d400-e274-11e8-9119-12736b166ad2.png)

**Comment by RubenMattan** [comment]
https://github.com/our-city-app/mobicage-ios-client/pull/78

**Comment by RubenMattan** [comment]
https://github.com/our-city-app/mobicage-android-client/pull/76

**Comment by bart-at-mobicage** [comment]
The app got rejected again. I don't know how he got to this state. Can you reproduce this when you only set your name and then reopen the profile page? Are the gender and age still 'unknown' then?

![screen shot 2018-11-08 at 09](https://user-images.githubusercontent.com/17762105/48186565-a3c3ec00-e338-11e8-9095-c83be5b0aff2.png)

**Comment by RubenMattan** [comment]
The user just reinstalled the app. These properties where already set that way
